name: Generate Snake

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kolkata

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: DHAANIBAHL
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
